apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-service
spec:
  selector:
    app: devops-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer 